version: '3'

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    #network_mode: "host"
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    volumes:
      - /home/mongo/data/db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    links:
#      - mongo-db:mongodb
#    depends_on:
#      - mongo-db
#    ports:
#      - 27018:8081
#    environment:
#      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin@123
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin123